language: "haskell"
install:
  - "travis_retry cabal install 'cpphs >= 1.18.3'"
  - "cabal install --dry-run -v3"
  - "travis_retry cabal install --force-reinstalls --only-dependencies"
script:
  - git clone https://github.com/faylang/fay-base.git
  - cabal install --jobs=1
  - cabal install fay-base/ --jobs=1
  - fay-tests --num-threads=4
notifications:
  irc:
    channels: "irc.freenode.net#fay"
    skip_join: true
  email:
    recipients: adam@bergmark.nl
    on_success: change
    on_failure: change
